# Generated by Django 5.1.2 on 2024-10-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loyalty_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pictures/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
