# Generated by Django 5.1.2 on 2024-10-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, choices=[('M', 'Manager'), ('CA', 'Cashier'), ('B', 'Bartender'), ('CO', 'Cook'), ('W', 'Waiter'), ('WS', 'Waitress')], max_length=100, null=True),
        ),
    ]
