# Generated by Django 5.1.2 on 2024-11-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='dummy.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
