# Generated by Django 5.1.2 on 2024-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='dummy.png', upload_to='profile_pictures/'),
        ),
    ]
