# Generated by Django 5.1.2 on 2024-10-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_photo',
            field=models.ImageField(default='category_photos/default.jpg', upload_to='category_photos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(default='product_photos/default.jpg', upload_to='product_photos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
