# Generated by Django 5.1.2 on 2024-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='fav_icon',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo/', verbose_name='Fav Icon'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='slogan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Slogan'),
        ),
    ]
