# Generated by Django 5.1.1 on 2024-11-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_information', '0002_siteinfo_fav_icon_siteinfo_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='slogan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Slogan'),
        ),
    ]
