# Generated by Django 5.1.2 on 2024-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Registered'), ('A', 'Approved'), ('CA', 'Cancelled'), ('CK', 'Cooking'), ('C', 'Completed')], default='P', max_length=20),
        ),
    ]
