# Generated by Django 5.1.2 on 2024-10-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Cash'), ('I', 'Internet')], default='C', max_length=20),
        ),
    ]
