# Generated by Django 5.1.2 on 2024-11-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('CA', 'Cancelled'), ('CK', 'Cooking'), ('C', 'Completed')], default='P', max_length=20),
        ),
    ]
