# Generated by Django 5.1.2 on 2024-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(default='table_qrcode/default.png', upload_to='table_qrcode/'),
        ),
    ]
