# Generated by Django 5.1.1 on 2024-11-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_table_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('TAKEAWAY', 'بیرون بر')], default='ACTIVE', max_length=10),
        ),
    ]
