# Generated by Django 5.1.1 on 2024-11-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
    ]
